# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
# restore packages
- script: dotnet restore
  displayName: 'restoring packages'

# run build
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

# after build, run tests
- task: DotNetCoreCLI@2
  displayName: 'run tests'
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

# pack for web deploy
# do this after you've built your app, near the end of your pipeline in most cases
# for example, you do this before you deploy to an Azure web app on Windows
- task: DotNetCoreCLI@2
  displayName: "pack for webdeploy - publish"
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True

# copy files to artifact staging directory
#- script: dotnet publish --output $(Build.ArtifactStagingDirectory)
#  displayName: "copy to artifact staging directory"

# publish artifacts
- task: PublishBuildArtifacts@1
  displayName: 'Publishing Artifacts'
